### ISSUE TITLE
[RESEARCH] Linking C++ libraries

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#1932]
This issue is to discuss ways of possibly supporting linking to C++ libraries. Once we have some better ideas on how to approach this, we can set up a project to implement whatever is needed.

**Todo list**
- [x] Decide which ABI breaking compiler flags we want to support
- [x] Decide if we want to use a pkg manager like Conan for Binary storage, or if we want to make folders on /opt for the different combinations (could also be a hash instead of everything spelled out)
- [x] If Conan, figure out how to set up and use the server (the supplied one, not the JFrog one)
- [x] Code library installer
- [x] Build environment for CE (https://github.com/compiler-explorer/compiler-explorer/pull/1945)
- [x] Library builder (https://github.com/compiler-explorer/infra/pull/346)

- [x] Code CE support to include linking to libraries
- [x] This means naming the libs (eg. fmtd, to link to libfmtd.a)
- [x] libs.fmt.staticliblink=fmtd doesn't work currently, you have to add it to every single version, but this is not practical
- [x] And code to fetch the .a files for the right combination of compiler/version/arch/flags/etc (this ofc requires us to know which ones we're going to support)

**Related Linking issues**
- does not fix 572
- [x] Fixes #1625
- [x] Fixes #1479
- [x] Fixes #1475
- [x] Obsoletes #1401
- [x] Fixes #1975
- [x] Closes #1662
- [x] Further supports #578
- [x] Fixes #578

**Comment by partouf** [comment]
First thing I researched was if we could maybe use Conan to do the heavy lifting of keeping track of binaries. (versus keeping them all on the EFS drive and keeping track manually)

So I (eventually) figured out that you can do the following things;

**Store built binaries into a store**
For example I used this to save binaries to the local cache
* A conanfile.py for a library
```
from conans import ConanFile, tools

class CrosscablesConan(ConanFile):
    name = "Crosscables"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"
    description = "Description of Crosscables here"
    url = "None"
    license = "None"
    author = "None"
    topics = None

    def package(self):
        self.copy("*.h", dst="include", src="include")
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["libGroundfloor", "libJumpropes"]
```
* The include/header folder is probably not relevant, we already have ways to figure that out and I don't think we should change that.
* Export to the local cache
  - `conan export-pkg . Crosscables/1.0@partouf/testing -s os=Linux -s compiler=gcc -s compiler.version=9 -s arch=x86_64 -s build_type=Debug -s compiler.libcxx=libstdc++`
  - There is importance in these variables as otherwise, the defaults for the system will be used, and we don't want that.
  - Conan makes a hash based on these variables, so they are be stored apart from each other.
  - I think if this is the route to take, we would maybe need to abuse certain variables to support more differentiating versions.

**Load library from store**
What I landed on was to create a new folder in where the source resided (so in production this would be in a sandboxed tmp folder).

And in this folder there needs to be conanfile.txt with something like this:
```
[requires]
Crosscables/1.0@partouf/testing
zlib/1.2.8

[imports]
lib, *.a -> .
```

There's also a way of requesting command line parameters for a compiler by supplying `[generators] compiler_args`, but this resulted in parameters without a library path to where the binaries resided. Which might be solvable (the zlib install for example did provide -L parameters), and at least the `conanbuildinfo.txt` (after running conan install) contains `[libdirs] /home/user/path-to-lib-folder` - so if we could read out this file, that would be Ok too.

But instead, I resolved it with telling conan to make copies of the .a files to the local folder (with the `[imports]` tag in the `conanfile.txt`), so all we would need is `-L./conan rpath etc`

To start the download you would need to execute `conan install . -s os=Linux -s compiler=gcc -s compiler.version=9 -s arch=x86_64 -s build_type=Debug -s compiler.libcxx=libstdc++` from the working folder where the conanfile.txt resides in.

**Remote server**
The aforementioned examples just work with a local cache. There is a way to setup a server and supplying `-r dns/ip` during the export-pkg and the install. I haven't tested this out yet, but this would be the way of distributing the libraries across the instances.

**Conclusion**
The question, of course, is how relevant this all is - after all, it just copies around binaries.
But then again it would save us from having to store the binaries on the EFS in a certain path structure that might not be entirely correct from the start. If conan has enough -s variables for what we need, this will simplify the process. But it also requires us to do an extra execution before linking, and have disk space to cache the libraries.

There is still a lot to figure out here, but it looks definitely possible.

**Comment by partouf** [comment]
Figured out how to make libraries that use cmake, to compile to other targets.

For this I cloned googletest and did the following:
* Create a build folder, cd to it
* Run the following script
```
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++

cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_SYSTEM_PROCESSOR=i386 "-DCMAKE_CXX_FLAGS_DEBUG=-m32 -fexceptions" ..
make
```
 - This is to force cmake to use Clang, do a Debug build, and have extra CXX flags for whatever we need, in this case it's -m32
 - I'm not entirely sure if MAKE_SYSTEM_PROCESSOR is actually needed, but it wasn't enough on its own, the CXX flags were needed
 - Checked if it actually produced 32bit .a's with calling nm lib/libgtestd.a and seeing if there were 32 bit addresses

**Conclusion**
So I think at least with libraries that use CMake, (and have set up their project correctly to not force their own CXX flags for example), we for loop over all the possible iterations of compilers and flags and build the library for those iterations.

The next question is how to figure out which combinations we need to produce binaries for.
And if we want to support libraries that don't use cmake, how to do that.

**Comment by partouf** [comment]
How to figure out what flags/situations cause the linker to require different library binaries.

I personally have more experience in this with MSVC than any other compiler, but I know some things. I hope we can further expand this list as we talk about this subject.

**Known variables**
* Architecture, this makes addresses and assembly different
  - but the question is what should we support. For linking to OpenSSL we currently only have x86_64 and x86. For other architectures, we can pose the question of how useful these will be, as it will still not allow execution in most if not all cases.
* Debug/Release, this produces differently mangled names usually
  - but since we always use -g when compiling, we could leave this to only support Debug builds.
* Compiler, every compiler does something different
  - isn't it great! :cries:
* C++ Standard, some (might) break binary compatibility
  - but some libraries might not support older or even other standards than what it's made to be built with - what to do about this, will the compiler complain about this enough already during regular compilation, or do we need more checks builtin to CE for this
* OS, changes system calls, bootstrap, mem model, register use, whatever else
  - probably not relevant if we only generate what we can run on, aka Linux

**What else is there?**
I know on Windows, there are also things like; which Runtime version is used and which threading type /MT etc, exceptions yes/no matters. But for Linux that might be a bit simpler.

I don't know if -fexceptions matters, but probably not?
Which other flags change the ABI?

**Dependencies**
If a library depends on some other library, we need to map this out and build one before the other.
What about OS library dependencies, do we need to take these into account?

**Comment by partouf** [comment]
**Libraries that use CMake**
* benri/v2.1.1
* benri/v2.0.1
* glm/0.9.8.5
* glm/0.9.9.4
* glm/0.9.9.8
* glm/trunk
* glm/0.9.9.0
* glm/0.9.9.6
* glm/0.9.9.2
* glm/0.9.9.5
* glm/0.9.9.1
* glm/0.9.9.7
* glm/0.9.9.3
* eigen/v3.3.4
* eigen/vtrunk
* eigen/v3.3.5
* eigen/v3.3.7
* xtl/test
* xtl/0.5.3
* xtl/trunk
* xtl/0.4.16
* cmcstl2
* cctz
* nlohmann_json/v3.1.2
* nlohmann_json/trunk
* nlohmann_json/v2.1.1
* nlohmann_json/v3.6.0
* PEGTL/trunk
* PEGTL/2.8.0
* outcome
* spy/trunk
* spy/0.0.3
* doctest/2.2.0
* doctest/2.3.7
* doctest/1.2.9
* doctest/trunk
* doctest/2.3.3
* doctest/2.3.1
* doctest/2.2.2
* doctest/2.3.5
* doctest/2.0.0
* doctest/2.3.0
* doctest/2.2.1
* doctest/2.3.4
* doctest/2.3.2
* doctest/2.2.3
* doctest/2.3.6
* doctest/2.1.0
* doctest/2.0.1
* GSL/v2.0.0
* GSL/v3.0.0
* GSL/v2.1.0
* GSL/v1.0.0
* GSL/tests
* blaze/trunk
* blaze/v3.5
* blaze/v3.3
* blaze/v3.7
* blaze/v3.6
* blaze/v3.4
* hfsm/trunk
* hfsm/0.8
* hfsm/0.10
* ctre/master
* ctre/dfa
* gsl-lite
* eastl/3.13.05
* eastl/trunk
* eastl/3.14.00
* eastl/3.14.06
* eastl/3.12.08
* eastl/3.13.03
* eastl/3.14.02
* eastl/3.12.04
* eastl/3.13.06
* eastl/3.12.07
* eastl/3.15.00
* eastl/3.13.02
* eastl/3.14.01
* eastl/3.13.00
* eastl/3.12.01
* eastl/3.16.05
* eastl/3.13.04
* eastl/3.14.03
* eastl/3.16.01
* ctbignum
* rangesv3/0.4.0
* rangesv3/trunk
* rangesv3/0.3.5
* rangesv3/0.9.1
* rangesv3/0.3.6
* rangesv3/0.10.0
* rangesv3/0.3.0trunk
* rangesv3/0.3.0
* nanorange
* catch2/v2.2.2
* catch2/v2.12.1
* catch2/v2.4.0
* catch2/v2.11.2
* catch2/trunk
* catch2/v2.8.0
* catch2/v2.7.1
* catch2/v2.6.0
* catch2/v2.4.2
* catch2/v2.10.1
* catch2/v2.11.0
* catch2/v2.9.1
* catch2/v2.2.3
* catch2/v2.4.1
* catch2/v2.11.3
* catch2/v2.5.0
* catch2/v2.10.0
* catch2/v2.7.2
* catch2/v2.9.0
* catch2/v2.6.1
* catch2/v2.7.0
* catch2/v2.10.2
* catch2/v2.12.0
* catch2/v2.11.1
* catch2/v2.3.0
* catch2/v2.9.2
* etl
* xsimd/trunk
* xsimd/7.0.0
* xsimd/6.1.4
* google-benchmark/trunk
* google-benchmark/v1.3.0
* google-benchmark/v1.2.0trunk
* google-benchmark/v1.2.0
* google-benchmark/v1.4.0
* googletest
* mp-units/trunk
* mp-units/v0.4.0
* mp-units/v0.3.1
* expected-lite/trunk
* expected-lite/v0.0.1
* expected-lite/v0.1.0
* cnl
* seastar/trunk
* seastar/seastar-18.08.0
* xtensor/test
* xtensor/0.17.4
* xtensor/trunk
* xtensor/0.19.4
* xtensor/benchmark
* xtensor/0.18.2
* libguarded/trunk
* dlib/trunk
* dlib/v19.7trunk
* dlib/v19.7
* dlib/v19.9
* dlib/v19.10
* opencv
* brigand/1.3.0
* brigand/trunk
* fmt/4.0.0
* fmt/trunk
* fmt/5.3.0
* fmt/6.1.1
* fmt/5.1.0
* fmt/6.0.0
* fmt/4.1.0
* fmt/5.0.0
* fmt/6.1.2
* fmt/6.1.0
* fmt/5.2.0

Note that some were installed without a /version. Also some might not actually need to be built, but have CMake for tests and whatnot.

**Comment by partouf** [comment]
**Libraries using Makefile**

* tbb/src
* nlohmann_json/v3.1.2
* nlohmann_json/trunk
* nlohmann_json/v2.1.1
* nlohmann_json/v3.6.0
* PEGTL/trunk
* PEGTL/2.8.0
* ctre/v2
* ctre/master
* ctre/ecma-unicode
* ctre/dfa

**Comment by partouf** [comment]
Fyi, I've begun work on getting the libraries into the python installer and get it to build from there as a separate step. Branch -> https://github.com/mattgodbolt/compiler-explorer-image/compare/libraries

**Comment by partouf** [comment]
Concerning compiler flags, I'm trying to find out which Clang flags change ABI, but the manual is less clear on this. https://clang.llvm.org/docs/UsersManual.html#controlling-code-generation

**Comment by partouf** [comment]
Found out that you can add new settings to the differentiation in Conan, so we wouldn't have to abuse a setting to get all the combinations we want. https://docs.conan.io/en/latest/extending/custom_settings.html#adding-new-settings

**Comment by partouf** [comment]
Concerning compiler versions, there seems to be just 1 number for version in for example these fmt binaries https://conan.io/center/fmt/6.2.0/?user=_&channel=_&revision=&os=Linux&tab=config&arch=x86_64&compiler=gcc
So it just says gcc v9, v8, v7, etc. no minor/build numbers in the version. So I'm wondering, are these actually binary compatible with each other? Really? No abi bugfixes mid-major-version?

**Comment by partouf** [comment]
Concerning other architectures, I noticed that on gcc you can do --target-help and then you get a list of command line parameters that can influence the target. Considering some compilers (that might be able to compile to binaries) are not x86, I used that for example to get a library to compile for raspbian10 (and thus to never try to build to x86).

I first tried it with the arduinouno compiler, but eventually found out that one doesn't really have support for stdlib, so that one will fail to build the library. Not sure if to keep that to fail or figure out some way to avoid compiling with it.

**Comment by partouf** [comment]
Building with raspbian10 seems to have produced a good static library. I was able to link against it and produce a binary by adding libs.fmt.versions.520.staticliblink=fmtd in the properties file, and manually adding the -rpath and -L to the compiler arguments.

**Comment by partouf** [comment]
Managed to build fmt 5.2.0 for a bunch of compilers I have on my CE VM, most support x86_64, the older versions of clang don't support x86, and all the arm/ppc/mips/etc compilers for their native target.

I think I have a sense of that it's working, but I'm going to try some other libraries.

Linux clang armv7-clang-trunk (libc++)
Linux clang clang350 (libstdc++)
Linux clang clang351 (libstdc++)
Linux clang clang352 (libstdc++)
Linux clang clang36x (libstdc++)
Linux clang clang371 (libstdc++)
Linux clang clang37x (libstdc++)
Linux clang clang380 (libstdc++)
Linux clang clang381 (libstdc++)
Linux clang clang390 (libstdc++)
Linux clang clang391 (libstdc++)
Linux clang clang400 (libstdc++)
Linux clang clang401 (libstdc++)
Linux clang clang500 (libc++)
Linux clang clang500 (libstdc++)
Linux clang clang600 (libc++)
Linux clang clang600 (libstdc++)
Linux clang clang800 (libc++)
Linux clang clang800 (libstdc++)
Linux clang clang_trunk (libc++)
Linux clang clang_trunk (libstdc++)
Linux ellcc ellcc170716 (libstdc++)
Linux gcc aarchg54 (libstdc++)
Linux gcc arm64g630 (libstdc++)
Linux gcc arm64g640 (libstdc++)
Linux gcc arm64g730 (libstdc++)
Linux gcc arm64g820 (libstdc++)
Linux gcc armg630 (libstdc++)
Linux gcc armg640 (libstdc++)
Linux gcc armg730 (libstdc++)
Linux gcc armg820 (libstdc++)
Linux gcc armhfg54 (libstdc++)
Linux gcc frc2019 (libstdc++)
Linux gcc g481 (libstdc++)
Linux gcc g482 (libstdc++)
Linux gcc g483 (libstdc++)
Linux gcc g484 (libstdc++)
Linux gcc g485 (libstdc++)
Linux gcc g490 (libstdc++)
Linux gcc g491 (libstdc++)
Linux gcc g492 (libstdc++)
Linux gcc g493 (libstdc++)
Linux gcc g510 (libstdc++)
Linux gcc g520 (libstdc++)
Linux gcc g530 (libstdc++)
Linux gcc g540 (libstdc++)
Linux gcc g550 (libstdc++)
Linux gcc g6 (libstdc++)
Linux gcc g62 (libstdc++)
Linux gcc g64 (libstdc++)
Linux gcc g73 (libstdc++)
Linux gcc g74 (libstdc++)
Linux gcc g81 (libstdc++)
Linux gcc g82 (libstdc++)
Linux gcc g83 (libstdc++)
Linux gcc g91 (libstdc++)
Linux gcc g92 (libstdc++)
Linux gcc gcxx-modules-trunk (libstdc++)
Linux gcc gsnapshot (libstdc++)
Linux gcc mips5 (libstdc++)
Linux gcc mips564 (libstdc++)
Linux gcc mips564el (libstdc++)
Linux gcc ppc64g8 (libstdc++)
Linux gcc ppc64leg630 (libstdc++)
Linux gcc ppc64leg8 (libstdc++)
Linux gcc ppcg48 (libstdc++)
Linux gcc raspbian10 (libstdc++)
Linux gcc raspbian9 (libstdc++)
Linux gcc riscv820 (libstdc++)

**Comment by mattgodbolt** [comment]
Amazing stuff: thank you @partouf

**Comment by mattgodbolt** [comment]
>  If Conan, figure out how to set up and use the server (the supplied one, not the JFrog one)

I've had some experience with this: it's pretty straightforward. We can probably run it on the admin node and point it at EFS, or else we can run a dedicated node and use local storage or something like that.

**Comment by partouf** [comment]
> > If Conan, figure out how to set up and use the server (the supplied one, not the JFrog one)
> 
> I've had some experience with this: it's pretty straightforward. We can probably run it on the admin node and point it at EFS, or else we can run a dedicated node and use local storage or something like that.

@apmorton mentioned earlier in slack that it's probably a bad idea to use EFS for this. A dedicated node with local storage, ideally also that doesn't disappear when the node goes down for some reason.
Also ideally with the port exposed so that we can push binaries to it from home so we don't have to bother the admin node to build all the libraries for 10 days straight.

So far it doesn't look like it's going to be a lot of diskspace, I have 17MB on the server for the binaries (just libfmtd.a actually) of fmt v5.2.0, but I don't have all compilers locally. Nor am I sure if these are all the needed configuration combinations. But around 20MB per library version seems Ok.

**Comment by partouf** [comment]
The install command I've landed on, now is
`conan install . -r myserver -s os=Linux -s compiler=gcc -s compiler.version=raspbian10 -s compiler.libcxx=libstdc++ -s arch= -s build_type=Debug -s stdver= -s flagcollection=`

(These variables are used during export as well and require the client's settings.yml to be altered. Will probably commit this later along with the rest. Also, the remote needs to be added before trying this.)

Perhaps not needed, but there is a way to do this without the client and just via nodejs with a couple of REST calls;
* /v1/conans/fmt/5.2.0/fmt/5.2.0/search
* Locate hash of best match
* /v1/conans/fmt/5.2.0/fmt/5.2.0/packages/**HASH**/download_urls
* Follow the URL with key 'conan_package.tgz'
* Untargz and save the .a files to disk

**Comment by partouf** [comment]
As another confirmation that compiler flags aren't that intrusive, I looked up some top used compiler arguments and tried a bunch of things. This was with a simple fmt example, so it could always be a different situation with more complex code.

* -march=hasswell/skylake/broadwell against a x86_64 built library works fine (makes sense, of course, those are 64bit cpu's after all and API/ABI bits don't need fancy cpu features besides the basics)
* different optimizations don't matter of course
* c++ version matters sometimes, but the library usually is built with a specific version and will produce an error through the header files, so it will error during compilation preventing linking and thus we wouldn't have to build the library for all kinds of versions
* stdc++/stdlibc++, that definitely matters, so once you give the Conan install command that variable, it will compile again
* --target= matters, but I'm not sure we have a lot of headers installed for other targets than x86/x86-64 - at least not for the generic compilers (for the compilers that are meant to work with that target it should work through leaving arch= empty like with e.g. raspbian10)

**Comment by partouf** [comment]
Trying to build TBB, which doesn't use cmake, so there are quite some limitations.
Also, it generates a shared library, so I have to figure out how that works.

As for different builds, I can do `make` with a new compiler (using export cc= and cxx=), but it doesn't offer any way to supply any other options like arch or toolchain.

So I'm not actually sure how much will actually work. Only really x86-64 seems to be possible.

**Comment by partouf** [comment]
"Solved" issue by using readelf to see if the right arch is built and ldd to see if it's linked against the correct stdlibc++/libc++

But the paths are still not correct because I couldn't set the toolchain and rpaths, could I use LD_LIBRARY_PATH ? Would be a lot of effort to code though

**Comment by partouf** [comment]
With my AWS test account, I'm finding out that you can keep a disk once the instance has shutdown. 

I'm hoping that I can set it up as LVM so it's "easy" to enlarge with more space if needed. And then I need to figure out a script and configuration for the instance startup.

**Comment by partouf** [comment]
Kind of worried about the build times of some libraries. Some take a really long time.

Currently, only git changes or new compilers/combinations that haven't been build for will cause ce_install build to build the library. But because we have so many compilers, it adds up to a dark abyss of compilation - no matter where or how we do the building.

I'm beginning to think that maybe we should only build combinations that are regularly (or at all) used. But how do we have approach a thing like that?

**Comment by partouf** [comment]
> Kind of worried about the build times of some libraries. Some take a really long time.
> 
> Currently, only git changes or new compilers/combinations that haven't been build for will cause ce_install build to build the library. But because we have so many compilers, it adds up to a dark abyss of compilation - no matter where or how we do the building.
> 
> I'm beginning to think that maybe we should only build combinations that are regularly (or at all) used. But how do we have approach a thing like that?

Wondering if anyone can help me think about this problem? @mattgodbolt @apmorton @RabsRincon 
I took a look at the Google analytics, but I don't think compiler+library information is stored in anyway.
Would it be an ok idea to collect compiler+library numbers (basically just the combination as a key and increment per compilation) on the backend? Maybe store it in a light AWS database thingy.

That way we can determine which compiler and library combinations should actually be built, instead of building * everything *.

**Comment by partouf** [comment]
Was wondering if a mismatch between a static library being built with libc++ would result in horrible errors if say you would have a function return an std::string compiled with libc++ and then the example program thinking its a stdlibc++ std::string and having all kinds of disastrous results.

But I found out that you get a linking error, as the types are differently mangled. (abi:cxx11)

I think this is mainly a good thing, but this might also mean we have to maybe try and build libraries with both types of stdlib.
The trouble with that, unfortunately, is that I'm unsure how to recognize something build with libc++, as some libraries might ignore a stdlib flag change.

**Comment by partouf** [comment]
Perhaps, a thing we could do is a `readelf -s libfile.a` and see if some mangled names have "cxx11" in their signature, which would indicate it's been compiled with the (default these days) cxx11 abi and thus - perhaps maybe - not with libc++. But it's probably not very reliable.

**Comment by partouf** [comment]
Or perhaps better to look for `__gxx_personality_v0` ?

**Comment by partouf** [comment]
Comparison using example

```c++
partouf@ubi2:/opt/compiler-explorer/libs/abitest$ cat abitest.hpp
#pragma once

#include <string>

std::string getStdString(const char *value);
partouf@ubi2:/opt/compiler-explorer/libs/abitest$ cat abitest.cpp
#include "abitest.hpp"

std::string getStdString(const char *value) {
    return std::string(value);
}
```


With `-std=libc++` (Clang-8.0.0)
```
Symbol table '.symtab' contains 19 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS abitest.cpp
     2: 0000000000000000     0 SECTION LOCAL  DEFAULT    2
     3: 0000000000000000     0 SECTION LOCAL  DEFAULT    5
     4: 0000000000000000     0 SECTION LOCAL  DEFAULT    8
     5: 0000000000000000     0 SECTION LOCAL  DEFAULT   11
     6: 0000000000000000     0 SECTION LOCAL  DEFAULT   14
     7: 0000000000000000     0 SECTION LOCAL  DEFAULT   17
     8: 0000000000000000     0 SECTION LOCAL  DEFAULT   20
     9: 0000000000000000    38 FUNC    GLOBAL DEFAULT    2 _Z12getStdStringPKc
    10: 0000000000000000    27 FUNC    WEAK   DEFAULT   11 _ZNSt3__111char_traitsIcE
    11: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZNSt3__112basic_stringIc
    12: 0000000000000000    71 FUNC    WEAK   HIDDEN     5 _ZNSt3__112basic_stringIc
    13: 0000000000000000    49 FUNC    WEAK   DEFAULT    8 _ZNSt3__117__compressed_p
    14: 0000000000000000    34 FUNC    WEAK   HIDDEN    14 _ZNSt3__122__compressed_p
    15: 0000000000000000    27 FUNC    WEAK   HIDDEN    17 _ZNSt3__122__compressed_p
    16: 0000000000000000    10 FUNC    WEAK   HIDDEN    20 _ZNSt3__19allocatorIcEC2E
    17: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND memset
    18: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND strlen
```

Without flags:
```
Symbol table '.symtab' contains 11 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS abitest.cpp
     2: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT    4 GCC_except_table0
     3: 0000000000000000     0 SECTION LOCAL  DEFAULT    2
     4: 0000000000000000     0 SECTION LOCAL  DEFAULT    4
     5: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _Unwind_Resume
     6: 0000000000000000   115 FUNC    GLOBAL DEFAULT    2 _Z12getStdStringB5cxx11PK
     7: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZNSaIcEC1Ev
     8: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZNSaIcED1Ev
     9: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZNSt7__cxx1112basic_stri
    10: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __gxx_personality_v0
```

**Comment by partouf** [comment]
This is now live. New thread -> https://github.com/compiler-explorer/compiler-explorer/issues/2079
