### ISSUE TITLE
Frontend TypeScript conversion tracking thread

### ISSUE THREAD

**Issue by matsjla** [compiler-explorer/compiler-explorer#2981]
We are currently in the process of migrating the entire frontend code to TypeScript.

This code can be found inside the `static` folder at the root of tree.

## Files that need conversion

- [x] analytics.js (depends on options.js)
- [x] ansi-to-html.js (no dependencies) https://github.com/compiler-explorer/compiler-explorer/pull/2988
- [x] codelens-handler.js (no dependencies) https://github.com/compiler-explorer/compiler-explorer/pull/2990
- [x] colour.js (no dependencies) https://github.com/compiler-explorer/compiler-explorer/pull/2991
- [x] compiler-picker.js (depends on analytics.js, local.js) https://github.com/compiler-explorer/compiler-explorer/pull/3436
- [x] compiler-service.js (depends on options.js) https://github.com/compiler-explorer/compiler-explorer/pull/3672
- [x] components.js (no dependencies) https://github.com/compiler-explorer/compiler-explorer/pull/2993
- [x] fontscale.js (depends on options.js)
- [x] history-widget.js (depends on analytics.js, history.js) https://github.com/compiler-explorer/compiler-explorer/pull/3346
- [x] history.js (depends on local.js, sharing.js) https://github.com/compiler-explorer/compiler-explorer/pull/3337
- [x] hub.js (depends on components.js, panes/*.js, compiler-service.js) (assigned to @matsjla) https://github.com/compiler-explorer/compiler-explorer/pull/3470
- [x] libs-widget-ext.js (depends on options.js, local.js) https://github.com/compiler-explorer/compiler-explorer/pull/3077
- [x] load-save.js (depends on analytics.js, local.js, history.js) https://github.com/compiler-explorer/compiler-explorer/pull/3345
- [x] local.js (depends on options.js) https://github.com/compiler-explorer/compiler-explorer/pull/3053
- [x] main.js (depends on components.js, hub.js, settings.js, local.js, themes.js, motd.js, simplecook.js, history-widget.js, history.js, presentation.js) https://github.com/compiler-explorer/compiler-explorer/pull/4520
  - We probably want to do this once most other files have been migrated, as this file depends on a lot of stuff!
- [x] motd.js (depends on analytics.js)
- [x] noscript.js (depends on toggles.js) https://github.com/compiler-explorer/compiler-explorer/pull/3420
- [x] options.js (no dependencies) https://github.com/compiler-explorer/compiler-explorer/pull/2982
- [x] presentation.js (depends on local.js) https://github.com/compiler-explorer/compiler-explorer/pull/3395
- [x] settings.js (depends on colour.js, themes.js, options.js, local.js) https://github.com/compiler-explorer/compiler-explorer/pull/3297
- [x] simplecook.js (no dependencies) https://github.com/compiler-explorer/compiler-explorer/pull/3010
- [x] themes.js (no dependencies) https://github.com/compiler-explorer/compiler-explorer/pull/3332
- [x] timing-info-widget.js https://github.com/compiler-explorer/compiler-explorer/pull/3424
- [x] toggles.js (no dependencies) https://github.com/compiler-explorer/compiler-explorer/pull/3344
- [x] In addition to these files, all of the files in `/static/modes/*.js` need conversion. None of these files have any dependencies.
- And all the remaining panes in `static/panes/`:
  - [x] compiler.js (depends on components.js)
  - [x] conformance-view.js (depends on components.js)
  - [x] device-view.js (no dependencies)
  - [x] diff.js (no dependencies) (assigned to @jeremy-rifkin) https://github.com/compiler-explorer/compiler-explorer/pull/3676
  - [x] editor.js (depends on components.js)
  - [x] executor.js (no dependencies) https://github.com/compiler-explorer/compiler-explorer/pull/4605
  - [x] tool.js (depends on components.js) https://github.com/compiler-explorer/compiler-explorer/pull/4474

## Which files should I start with?

It is easiest to migrate code that doesn't depend on other JS files. New contributors are recommended to start migrating files with zero dependencies.

## I want to contribute!

Once you've selected a file you wish to work on, please comment on this issue so it's easier to track who is working on what. Thanks!

**Comment by MarkusJx** [comment]
I could help out with ``ansi-to-html.js``, ``codelens-handler.js``, ``colour.js`` and ``components.js``. Please let me know if that's ok and I'll start working on those files.

**Comment by supergrecko** [comment]
> I could help out with `ansi-to-html.js`, `codelens-handler.js`, `colour.js` and `components.js`. Please let me know if that's ok and I'll start working on those files.

That'd be great! I think the first three are easier to deal with. Components.js exports quite a few functions which take arguments that are component-specific. Let us know if you need help with those!

While we're at it; we like to keep public interfaces related to a file in a `.interfaces.ts` file. Each ts file has to be added to the tsconfig.json (looking for a better solution here), and there is currently no linting set up for TS.

Thanks for showing interest!

**Comment by MarkusJx** [comment]
Okay, I'm pretty much done with converting ``ansi-to-html.js`` but the ``ansi-to-html-tests`` fail since the file is now written in typescript and therefore has to be compiled to javascript before running the tests, but this of course doesn't happen, thus, the test phase fails.
Any suggestions on how to solve this? Maybe use something like ``ts-node`` to compile the typescript code before executing the tests?

**Comment by aneeshrelan** [comment]
Can I take up `toggles.js` since it's my first time and it has no dependencies?

**Comment by supergrecko** [comment]
> Okay, I'm pretty much done with converting `ansi-to-html.js` but the `ansi-to-html-tests` fail since the file is now written in typescript and therefore has to be compiled to javascript before running the tests, but this of course doesn't happen, thus, the test phase fails. Any suggestions on how to solve this? Maybe use something like `ts-node` to compile the typescript code before executing the tests?

Great question, I think we probably want to set up some ts-node like infrastructure for running typescript tests further down the line (maybe ts-mocha?).

In either case, could you submit a patch with the ansi-to-html change, and then we can discuss how we want to deal with those tests in that thread?

**Comment by supergrecko** [comment]
> Can I take up `toggles.js` since it's my first time and it has no dependencies?

Yes, that'd be great, thank you!

**Comment by MarkusJx** [comment]
> > Okay, I'm pretty much done with converting `ansi-to-html.js` but the `ansi-to-html-tests` fail since the file is now written in typescript and therefore has to be compiled to javascript before running the tests, but this of course doesn't happen, thus, the test phase fails. Any suggestions on how to solve this? Maybe use something like `ts-node` to compile the typescript code before executing the tests?
> 
> Great question, I think we probably want to set up some ts-node like infrastructure for running typescript tests further down the line (maybe ts-mocha?).
> 
> In either case, could you submit a patch with the ansi-to-html change, and then we can discuss how we want to deal with those tests in that thread?

In theory, I could do that, but the test are executed on commit and if they fail, I am unable to commit my changes. Is there any way to disable the test execution for that specific commit?

**Comment by supergrecko** [comment]
> > > Okay, I'm pretty much done with converting `ansi-to-html.js` but the `ansi-to-html-tests` fail since the file is now written in typescript and therefore has to be compiled to javascript before running the tests, but this of course doesn't happen, thus, the test phase fails. Any suggestions on how to solve this? Maybe use something like `ts-node` to compile the typescript code before executing the tests?
> > 
> > 
> > Great question, I think we probably want to set up some ts-node like infrastructure for running typescript tests further down the line (maybe ts-mocha?).
> > In either case, could you submit a patch with the ansi-to-html change, and then we can discuss how we want to deal with those tests in that thread?
> 
> In theory, I could do that, but the test are executed on commit and if they fail, I am unable to commit my changes. Is there any way to disable the test execution for that specific commit?

You can ignore the git checks with the -n flag to git commit

**Comment by MarkusJx** [comment]
I'd also like to convert ``simplecook.js`` and maybe do some more once ``options.js`` is fully converted & merged

**Comment by partouf** [comment]
Also related to this: https://github.com/compiler-explorer/compiler-explorer/issues/3015

**Comment by jeremy-rifkin** [comment]
I'll work on `compiler-picker.js`

**Comment by LukaPrebil** [comment]
Ill work on `executor.js`

**Comment by MarkusJx** [comment]
I think after one year I could do some more of this (I can't figure out why I'm back :D). So I'd like to work on ``compiler.js``, ``conformance-view.js``, ``device-view.js`` and ``editor.js``. And maybe this year I've got actually time to help you finish this whole task, we'll see

**Comment by RubenRBS** [comment]
Thanks! The panes that are not yet ported over are the harder ones, given how long they are. I'd say device-view, conformance-view and tool are the easier ones in case you want to try one of those first

**Comment by MarkusJx** [comment]
I could also work on `executor.js` and `tools.js`

**Comment by mattgodbolt** [comment]
Amazing!

**Comment by RubenRBS** [comment]
Yayyy
