### ISSUE TITLE
Backend TypeScript conversion tracking thread

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#4645]
feWe are currently in the process of migrating our backend code to TypeScript.

This backend code can be found inside the `lib/` folder.

## Files that need conversion

- [x] lib/assert.ts
- [x] lib/aws.ts
- [x] lib/base-compiler.ts
- [x] lib/cfg.js (assigned @jeremy-rifkin) https://github.com/compiler-explorer/compiler-explorer/pull/4657
- [x] lib/clientstate-normalizer.js https://github.com/compiler-explorer/compiler-explorer/pull/4720
- [x] lib/clientstate.js https://github.com/compiler-explorer/compiler-explorer/pull/4719
- [x] lib/common-utils.ts
- [x] lib/compilation-env.ts
- [x] lib/compilation-queue.ts
- [x] lib/compiler-arguments.js #4692
- [x] lib/compiler-finder.ts
- [x] lib/csp.ts
- [x] lib/exec.ts
- [x] lib/instructionsets.ts
- [x] lib/keyed-type.interfaces.ts
- [x] lib/keyed-type.ts
- [x] lib/languages.ts
- [x] lib/lib.d.ts
- [x] lib/llvm-ast.ts
- [x] lib/llvm-ir.ts
- [x] lib/llvm-opt-transformer.ts
- [x] lib/logger.ts
- [x] lib/metrics-server.ts
- [x] lib/options-handler.ts
- [x] lib/packager.ts
- [x] lib/pe32-support.ts
- [x] lib/properties.interfaces.ts
- [x] lib/properties.ts
- [x] lib/s3-handler.interfaces.ts
- [x] lib/s3-handler.ts
- [x] lib/sponsors.interfaces.ts
- [x] lib/sponsors.ts
- [x] lib/stacktrace.ts
- [x] lib/symbol-store.ts
- [x] lib/toolchain-utils.ts
- [x] lib/utils.ts
- [x] lib/asm-docs
  - [x] _all.ts
  - [x] amd64.ts
  - [x] arm32.ts
  - [x] avr.ts
  - [x] base.ts
  - [x] evm.ts
  - [x] index.ts
  - [x] java.ts
  - [x] llvm.ts
  - [x] mos6502.ts
  - [x] python.ts
- [x] lib/buildenvsetup
  - [x] _all.ts
  - [x] base.ts
  - [x] buildenv.interfaces.ts
  - [x] ceconan-rust.ts
  - [x] ceconan.ts
  - [x] cliconan.ts
  - [x] index.ts
- [x] lib/cache
  - [x] base.interfaces.ts
  - [x] base.ts
  - [x] from-config.ts
  - [x] in-memory.ts
  - [x] multi.ts
  - [x] null.ts
  - [x] on-disk.ts
  - [x] s3.ts
- [x] lib/compilers https://github.com/compiler-explorer/compiler-explorer/pull/4609
  - [x] _all.js
  - [x] ada.ts
  - [x] analysis-tool.js
  - [x] argument-parsers.ts
  - [x] assembly.ts
  - [x] avrgcc6502.ts
  - [x] beebasm.ts
  - [x] carbon.ts
  - [x] cc65.ts
  - [x] circle.js
  - [x] circt.ts
  - [x] cl430.ts
  - [x] clang.ts
  - [x] clangcl.ts
  - [x] clean.js
  - [x] clspv.ts
  - [x] cppfront.ts
  - [x] cproc.js
  - [x] crystal.js
  - [x] dart.js
  - [x] default.js
  - [x] dmd.js
  - [x] dosbox-compiler.ts
  - [x] dotnet.ts
  - [x] ellcc.js
  - [x] erlang.ts
  - [x] ewarm.js
  - [x] ewavr.js
  - [x] fake-for-test.ts
  - [x] flang.ts
  - [x] fortran.ts
  - [x] gcc.ts
  - [x] gccrs.js
  - [x] golang.ts
  - [x] haskell.js
  - [x] hlsl.ts
  - [x] hook.ts
  - [x] index.js
  - [x] ispc.js
  - [x] jakt.ts
  - [x] java.js
  - [x] julia.ts
  - [x] kotlin.js
  - [x] ldc.js
  - [x] llc.js
  - [x] llvm-mca.js
  - [x] llvm-mos.ts
  - [x] mlir.ts
  - [x] mrustc.js
  - [x] nasm.js
  - [x] nim.js
  - [x] nvcc.js
  - [x] ocaml.js
  - [x] opt.js
  - [x] osaca.js
  - [x] pascal-utils.js
  - [x] pascal-win.js
  - [x] pascal.js
  - [x] pony.ts
  - [x] ppci.js
  - [x] ptxas.js
  - [x] python.ts
  - [x] racket.ts
  - [x] rga.ts
  - [x] ruby.ts
  - [x] rust.ts
  - [x] rustc-cg-gcc.js
  - [x] scala.js
  - [x] sdcc.js
  - [x] solidity.js
  - [x] spirv.ts
  - [x] swift.js
  - [x] tendra.js
  - [x] tinyc.js
  - [x] toit.ts
  - [x] turboc.ts
  - [x] typescript-native.js
  - [x] win32-vc.js
  - [x] win32-vc6.js
  - [x] win32.js
  - [x] wine-vc.js
  - [x] wsl-vc.js
  - [x] z88dk.ts
  - [x] zig.ts
  - [x] zigcc.ts
  - [x] zigcxx.ts
- [x] lib/demangler
  - [x] _all.ts
  - [x] base.ts
  - [x] cpp.ts
  - [x] default.ts
  - [x] index.ts
  - [x] llvm.ts
  - [x] nvhpc.ts
  - [x] pascal.ts
  - [x] prefix-tree.ts
  - [x] win32-llvm.ts
  - [x] win32.ts
- [x] lib/external-parsers
  - [x] _all.ts
  - [x] base.ts
  - [x] ce-asm-parser.ts
  - [x] external-parser.interface.ts
  - [x] index.ts
- [x] lib/formatters
  - [x] _all.ts
  - [x] base.interfaces.ts
  - [x] base.ts
  - [x] clang-format.ts
  - [x] dartformat.ts
  - [x] gofmt.ts
  - [x] index.ts
  - [x] rustfmt.ts
- [x] lib/handlers
  - [x] api.js https://github.com/compiler-explorer/compiler-explorer/pull/4704
  - [x] assembly-documentation.ts
  - [x] compile.interfaces.ts
  - [x] compile.ts
  - [x] formatting.js (assigned @matsjla) https://github.com/compiler-explorer/compiler-explorer/pull/4656
  - [x] health-check.ts
  - [x] noscript.js https://github.com/compiler-explorer/compiler-explorer/pull/4694
  - [x] route-api.js https://github.com/compiler-explorer/compiler-explorer/pull/4707
  - [x] site-templates.ts
  - [x] source.js (assigned @matsjla) https://github.com/compiler-explorer/compiler-explorer/pull/4662
- [x] lib/mapfiles
  - [x] map-file-delphi.ts
  - [x] map-file-vs.ts
  - [x] map-file.ts
- [x] lib/objdumper
  - [x] _all.ts
  - [x] base.ts
  - [x] binutils.ts
  - [x] da65.ts
  - [x] default.ts
  - [x] elftoolchain.ts
  - [x] index.ts
  - [x] llvm.ts
- [x] lib/parsers
  - [x] asm-parser-amdgpu.js https://github.com/compiler-explorer/compiler-explorer/pull/4653
  - [x] asm-parser-beebasm.js #4664 
  - [x] asm-parser-cc65.ts
  - [x] asm-parser-cpp.ts
  - [x] asm-parser-crystal.js #4666
  - [x] asm-parser-dart.js #4665
  - [x] asm-parser-dotnet.ts
  - [x] asm-parser-ewavr.js #4667
  - [x] asm-parser-sass.js #4678
  - [x] asm-parser-spirv.ts
  - [x] asm-parser-turboc.js #4679
  - [x] asm-parser-vc.js #4690
  - [x] asm-parser-vc6.js #4690
  - [x] asm-parser-z88dk.js #4691
  - [x] asm-parser.interfaces.ts
  - [x] asm-parser.ts
  - [x] asm-raw.js https://github.com/compiler-explorer/compiler-explorer/pull/4647
  - [x] asmregex.ts
  - [x] llvm-pass-dump-parser.ts
- [x] lib/shortener
  - [x] _all.ts
  - [x] base.ts
  - [x] default.ts
  - [x] google.ts
  - [x] index.ts
  - [x] tinyurl.ts
- [x] lib/sources
  - [x] browser.ts
  - [x] builtin.ts
  - [x] index.ts
- [x] lib/storage
  - [x] _all.ts
  - [x] base.ts
  - [x] index.ts
  - [x] local.ts
  - [x] null.ts
  - [x] remote.ts
  - [x] s3.ts
- [x] lib/tooling
  - [x] _all.ts
  - [x] base-tool.interface.ts
  - [x] base-tool.ts
  - [x] bbcdiskify-tool.js (assigned @scotran) https://github.com/compiler-explorer/compiler-explorer/pull/4693
  - [x] clang-format-tool.js (assigned @scotran)
  - [x] clang-query-tool.js (assigned @scotran)
  - [x] clang-tidy-tool.js (assigned @scotran) https://github.com/compiler-explorer/compiler-explorer/pull/4695
  - [x] compiler-dropin-tool.ts
  - [x] index.ts
  - [x] llvm-cov-tool.ts
  - [x] llvm-mca-tool.js https://github.com/compiler-explorer/compiler-explorer/pull/4718
  - [x] microsoft-analysis-tool.js https://github.com/compiler-explorer/compiler-explorer/pull/4718
  - [x] osaca-tool.js https://github.com/compiler-explorer/compiler-explorer/pull/4718
  - [x] pahole-tool.js https://github.com/compiler-explorer/compiler-explorer/pull/4718
  - [x] pvs-studio-tool.js https://github.com/compiler-explorer/compiler-explorer/pull/4718
  - [x] readelf-tool.js https://github.com/compiler-explorer/compiler-explorer/pull/4718
  - [x] rustfmt-tool.js https://github.com/compiler-explorer/compiler-explorer/pull/4718
  - [x] strings-tool.js https://github.com/compiler-explorer/compiler-explorer/pull/4718
  - [x] testing-tool.js https://github.com/compiler-explorer/compiler-explorer/pull/4718
  - [x] x86to6502-tool.js https://github.com/compiler-explorer/compiler-explorer/pull/4718

## Which files should I start with?

It is easiest to migrate code that doesn't depend on other JS files. New contributors are recommended to start migrating files with zero dependencies.

## I want to contribute!

Once you've selected a file you wish to work on, please comment on this issue so it's easier to track who is working on what. Thanks!

**Comment by matsjla** [comment]
I'll work on lib/handlers/formatting.js

**Comment by mattgodbolt** [comment]
thanks @matsjla

**Comment by scotran** [comment]
I'll take up`bbcdiskify-tool.js`. Currently in the process and have a few clarifying questions for the current code - what would be the best way to ask, starting a new issue thread?

**Comment by jeremy-rifkin** [comment]
Thank you! Our discord would probably be the best place to ask but an issue thread would also be fine.

**Comment by scotran** [comment]
I can also do the 3 clang-*-tools.js

**Comment by jeremy-rifkin** [comment]
Thank you!

**Comment by jeremy-rifkin** [comment]
I'll work on lib/handlers/api

**Comment by jeremy-rifkin** [comment]
And that's everything in lib/ converted! Thank you everyone!
