### ISSUE TITLE
Testcases TypeScript conversion tracking thread

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#4660]
We are currently in the process of migrating our testcase code to TypeScript.

This code can be found inside the `test/` folder.

## Files that need conversion

- [x] _setup-log.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [ ] _setup.js
- [x] analysis-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4729
- [x] ansi-to-html-tests.ts https://github.com/compiler-explorer/compiler-explorer/pull/4659
- [x] asm-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] aws-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] base-compiler-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4729
- [x] base-formatter-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] cache-tests.js
- [x] cfg-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] check-img.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] checks.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] compilation-env.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] compiler-finder-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4729
- [x] csp-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] d-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [ ] demangler-tests.js
- [x] exec-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [ ] filter-tests.js
- [x] golang-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] google-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [ ] instructionsets-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] java-tests.js (assigned to @matsjla) https://github.com/compiler-explorer/compiler-explorer/pull/4698
- [x] lang-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] llvm-ast-parser-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4737
- [x] llvm-ir-parser-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4737
- [x] llvm-ir-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] llvm-pass-dump-parser-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4737
- [ ] map-file-tests.js
- [x] nim-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [ ] options-handler.js
- [ ] packager-tests.js
- [ ] pascal-tests.js
- [ ] pe32-tests.js
- [x] pp-output-test.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] ppci-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [ ] properties-test.js
- [x] rison.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [ ] sponsors-test.js
- [ ] statenormalisation-tests.js
- [x] symbol-store-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] tool-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [ ] unfurl-tests.js
- [ ] utils-tests.js
- [x] utils.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [ ] win-path-tests.js
- [ ] test/compilers
  - [ ] argument-parsers-tests.js
  - [ ] clang-tests.js
  - [ ] hook-tests.js
- [ ] test/handlers
  - [ ] api-tests.js
  - [x] asm-docs-tests.js (assigned to @matsjla) https://github.com/compiler-explorer/compiler-explorer/pull/4670
  - [ ] compile-tests.js
  - [ ] health-check-tests.js
  - [x] site-templates-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
  - [ ] source-tests.js
- [x] test/pp-output-cases
  - [x] filter-tests.js https://github.com/compiler-explorer/compiler-explorer/pull/4684
- [x] test/storage
  - [x] storage-s3-tests.js #4738
  - [x] storage-tests.js #4738

## Which files should I start with?

It is easiest to migrate code that doesn't depend on other JS files. New contributors are recommended to start migrating files with zero dependencies.

## I want to contribute!

Once you've selected a file you wish to work on, please comment on this issue so it's easier to track who is working on what. Thanks!

**Comment by Rounak-stha** [comment]
Are we waiting for something before porting the remaining tests to TS?
wanted to confirm because I'm working on a PR.

**Comment by jeremy-rifkin** [comment]
Hi @Rounak-stha, I think you should be good to go. There was some discussion about doing mocking better but I think that doesn't need to be a blocker for the ts conversion. The only thing is you may have to fudge the types a lot to get the tests compiling 😄

**Comment by Rounak-stha** [comment]
One thing that's blocking me is that in one of the test files, a protected member is being accessed and I might have to create a getter for it. I was hoping to updating only the test files but looks like I might have to touch other ones too.
Just wanted to be sure that's something we can do for this issue?

**Comment by jeremy-rifkin** [comment]
That's a good question, I'm not sure the best answer. One way to do it without altering non-test code would be
```ts
class TestFoo extends Foo {
    public bar() {
        return super.bar();
    }
}
```

**Comment by jeremy-rifkin** [comment]
And now resolved :)
