### ISSUE TITLE
[BUG]: Copperspice issue tracking

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#5221]
### Describe the bug

Example that sort of works:

- With gui but only compile - https://godbolt.org/z/WMG589TGv
- Gui disabled but executing - https://godbolt.org/z/cffsbqe3j

Commit done based on this:
https://github.com/compiler-explorer/compiler-explorer/commit/51529dad43b3974c895c9e95db8afefa0ef7a28f

Todo

- [x] Push to prod
- [ ] Any kind of `-lCsGui1.8` triggers gl linker errors, so it's not added by default - can we still somehow link against this?
- [ ] Consider https://utho.com/docs/tutorial/how-to-install-the-opengl-library-on-ubuntu-20-04/
- [ ] And if done, install newer version
- [ ] Test if we can generate the ui header files with a cmake project (requires the `uic` compiler provided by cs, see https://github.com/janwilmans/copperspice-gettingstarted)

### Steps to reproduce

-

### Expected behavior

-

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment]
gtgui include dir is now automatically added so that gui code now compiles

**Comment by partouf** [comment]
The example https://cppcoach.godbolt.org/z/jecoed4hh was given to me via twitter, the solution to this error would be to create a new folder next to the executable called `platforms`, where the libCsGuiXcb.*.so is copied to, and possibly adding libCsSupport*.so to the executable directory. There isn't really a mechanism for that for libraries, but I can setup a prototype that does this and see if that makes the example execute.

**Comment by partouf** [comment]
I have tried to do this by plopping this down in the code:
```
        const platformsDir = path.join(dirPath, 'platforms');
        await fs.mkdirp(platformsDir);
        await fs.copyFile('/opt/compiler-explorer/libs/copperspice/1.8.0/lib/CsGuiXcb1.8.so', path.join(platformsDir, 'CsGuiXcb1.8.so'));
```

But then I get the error message: `QXcbConnection: Could not connect to display`

**Comment by partouf** [comment]
There are a couple of runtime command line arguments you could pass, but those do not offer a way to dummy out the connection https://github.com/copperspice/copperspice/blob/d2fbcdc6391d64ce606334ba9523820b0626b284/src/plugins/platforms/xcb/xcb_support/qxcb_integration.cpp#L130

There also doesn't seem to be a way around this error generated here: https://github.com/copperspice/copperspice/blob/d2fbcdc6391d64ce606334ba9523820b0626b284/src/plugins/platforms/xcb/xcb_support/qxcb_connection.cpp#L595

(There are also other errors sprinkled around so even if we could circumvent that code it wouldn't work still)

I don't think we can make this work without introducing a plugin that mocks/dummies out the functionality.

The GLX version maybe has an offscreen buffer, but I'm betting it's based on the hardware characteristics of the intended destination display, so that wouldn't work either.

**Comment by partouf** [comment]
Technically I guess we could still link to CsGUI as long as users don't instantiate QApplication, but then anything else you do generates runtime error exit codes without message and so you can't really see what caused it.

**Comment by partouf** [comment]
Plan is to:
* make it link to CsGui1.8 by default
* add a runtime environment thing that installs the Xcb plugin in the right place

**Comment by janwilmans** [comment]
I think this will be as-good-as-we-can-make it for now and I will discuss additional improvements with the copperspice team
